osx_image: xcode11.5
language: swift
# xcode_project: DICE.xcodeproj
# xcode_scheme: DICE
# xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 11

script:
  - pod lib lint
  - set -o pipefail && xcodebuild build test -enableCodeCoverage YES -scheme DICE -workspace DICE.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.5,name=iPhone 11'

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'DICE'
