osx_image: xcode11.3
language: swift

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/DICE.xcworkspace -scheme DICE-Example -sdk iphonesimulator11.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
