osx_image: xcode11.5
language: swift
xcode_project: DICE.xcodeproj
xcode_scheme: DICE
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11

script:
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
